package com.example.juraj.note.data;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.example.juraj.note.data.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CART".
 */
@Entity(active = true)
public class Cart {

    @Id
    private Long id;

    @NotNull
    private String name;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient CartDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "cartId")
    })
    @OrderBy("date ASC")
    private List<CartItem> cartItems;

    @Generated
    public Cart() {
    }

    public Cart(Long id) {
        this.id = id;
    }

    @Generated
    public Cart(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCartDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<CartItem> getCartItems() {
        if (cartItems == null) {
            __throwIfDetached();
            CartItemDao targetDao = daoSession.getCartItemDao();
            List<CartItem> cartItemsNew = targetDao._queryCart_CartItems(id);
            synchronized (this) {
                if(cartItems == null) {
                    cartItems = cartItemsNew;
                }
            }
        }
        return cartItems;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetCartItems() {
        cartItems = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
