package com.example.juraj.note.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig cartDaoConfig;
    private final DaoConfig cartItemDaoConfig;

    private final NoteDao noteDao;
    private final CartDao cartDao;
    private final CartItemDao cartItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        cartDaoConfig = daoConfigMap.get(CartDao.class).clone();
        cartDaoConfig.initIdentityScope(type);

        cartItemDaoConfig = daoConfigMap.get(CartItemDao.class).clone();
        cartItemDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        cartDao = new CartDao(cartDaoConfig, this);
        cartItemDao = new CartItemDao(cartItemDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Cart.class, cartDao);
        registerDao(CartItem.class, cartItemDao);
    }
    
    public void clear() {
        noteDaoConfig.clearIdentityScope();
        cartDaoConfig.clearIdentityScope();
        cartItemDaoConfig.clearIdentityScope();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public CartDao getCartDao() {
        return cartDao;
    }

    public CartItemDao getCartItemDao() {
        return cartItemDao;
    }

}
